# Apa itu Neural Network (Jaringan Saraf Tiruan)
Neural Network (Jaringan Saraf Tiruan) adalah sistem komputasi yang dirancang meniru cara kerja otak manusia. Sistem ini belajar dari data untuk mengenali pola, membuat prediksi, atau mengambil keputusan.

Bayangkan seperti sekelompok orang yang bekerja sama di sebuah kantor: ada tim penerima data, tim analisis (yang bekerja di belakang layar), dan tim pembuat keputusan akhir.

![Cara Kerja Arsitektur Jaringan Saraf](https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcQh1tfzMUjeHSE2Q8f-uDY31C8eCuS68HU1pvBX16oFkty1KbdPhYXgKTPFeMkod-1w6kfh5AJfHRHwoP8)



## Struktur Komponen Utama (Arsitektur Jaringan)
Sebuah Neural Network umumnya terdiri dari tiga lapisan utama:

1. Input Layer (Lapisan Masukan): Berisi variabel-variabel atau fitur yang menjadi bahan dasar analisis. 

2. Hidden Layer (Lapisan Tersembunyi): Lapisan penengah tempat terjadinya kombinasi bobot dan perhitungan matematis untuk mengekstrak pola-pola abstrak dari data.

3. Output Layer (Lapisan Keluaran): Hasil akhir atau target yang diprediksi oleh model. 

## Alur Algoritma (Proses "Berpikir" Model)
Model Neural Network belajar secara berulang-ulang (looping) melalui dua tahap utama:
1. Forward Propagation (Umpan Maju)Model menerima nilai dari variabel input ($X$).Input tersebut dikalikan dengan Bobot ($w$) dan ditambah Bias ($b$). Rumus dasarnya:
$$z = (X_1 \cdot w_1) + (X_2 \cdot w_2) + (X_3 \cdot w_3) + b$$

> Hasil penjumlahan ($z$) dimasukkan ke dalam Fungsi Aktivasi (misalnya Sigmoid untuk klasifikasi biner) agar menghasilkan nilai prediksi   akhir     ($Y_{prediksi}$) antara 0 dan 1.

2. Backpropagation (Propagasi Balik)Model menghitung error atau tingkat kesalahan dengan membandingkan nilai $Y_{prediksi}$ dengan data asli ($Y_{aktual}$).Jika prediksinya salah atau tidak akurat, model akan berjalan mundur untuk menghitung ulang dan memperbaiki nilai bobot ($w$) serta bias ($b$) di setiap neuron.Proses ini terus diulang agar pada eksperimen berikutnya tingkat akurasi model menjadi semakin tinggi.

## Fungsi aktivasi Neural Network

### ReLU (Rectified Linear Unit)
ReLU adalah fungsi aktivasi yang paling populer dan menjadi standar bawaan (default) untuk hidden layer (lapisan tersembunyi) pada model deep learning.

Cara Kerja: Jika input bernilai negatif (kurang dari 0), fungsi akan mengubahnya menjadi 0 (neuron mati). Jika input bernilai positif, fungsi akan melewatkan nilai tersebut apa adanya.Rumus: 

$f(x) = \max(0, x)$

Kelebihan: Sangat cepat dihitung secara komputasi dan membantu mempercepat proses Backpropagation.

In [1]:
import math

# 1. DEFINISI FUNGSI AKTIVASI MURNI PYTHON

def relu(x):
    """Fungsi ReLU: Mengubah nilai negatif menjadi 0"""
    return max(0.0, x)

### Sigmoid
Fungsi ini mengubah nilai input apa pun menjadi rentang angka antara 0 dan 1.

Kegunaan Utama: Sangat cocok digunakan pada output layer (lapisan terakhir) untuk kasus Klasifikasi Biner (dua pilihan).Contoh Kasus SMK: Dalam simulasi kelulusan siswa yang ada pada dokumen Anda, 

fungsi Sigmoid digunakan di akhir model untuk memprediksi probabilitas status kelulusan: mendekati 0 berarti "Tidak Lulus", mendekati 1 berarti "Lulus".

Rumus: $f(x) = \frac{1}{1 + e^{-x}}$

In [2]:
def sigmoid(x):
    """Fungsi Sigmoid: Mengubah nilai menjadi rentang 0 hingga 1"""
    return 1.0 / (1.0 + math.exp(-x))


### Tanh (Hyperbolic Tangent)
Fungsi Tanh mirip dengan Sigmoid, tetapi rentang output yang dihasilkan berada di antara -1 dan 1.

Kelebihan: Karena pusatnya berada di angka 0 (zero-centered), fungsi ini sering kali membuat proses latihan model pada lapisan tersembunyi menjadi lebih efisien dibanding Sigmoid.

In [3]:
def tanh(x):
    """Fungsi Tanh: Mengubah nilai menjadi rentang -1 hingga 1"""
    return math.tanh(x)

### Softmax
Jika Sigmoid digunakan untuk dua pilihan (biner), Softmax digunakan untuk Klasifikasi Multikelas (lebih dari dua pilihan).

Cara Kerja: Fungsi ini menghasilkan probabilitas untuk setiap kelas, di mana total jumlah probabilitas dari seluruh pilihan tersebut adalah 1 (atau 100%).

Contoh Kasus: Memprediksi predikat kelulusan siswa: "Memuaskan", "Sangat Memuaskan", atau "Dengan Pujian (Cumlaude)".

In [4]:
def softmax(inputs):
    """Fungsi Softmax: Menghitung probabilitas untuk multikelas (total = 1)"""
    exp_values = [math.exp(x) for x in inputs]
    sum_exp_values = sum(exp_values)
    return [exp / sum_exp_values for exp in exp_values]

### SIMULASI NEURON (FORWARD PROPAGATION)

In [5]:
# 2. SIMULASI NEURON (FORWARD PROPAGATION)
# Kita gunakan contoh data siswa SMK: [Jam Belajar, Kehadiran, Nilai Praktik]
inputs = [12.0, 95.0, 85.0] 
weights = [0.5, 0.2, 0.8]    # Bobot untuk masing-masing input
bias = -15.0                 # Nilai bias awal

print("=== PROSES DI DALAM NEURON ===")

# Tahap 1: Menghitung kombinasi linear (Input * Bobot + Bias)
# Rumus: (x1*w1) + (x2*w2) + (x3*w3) + bias
linear_output = sum(x * w for x, w in zip(inputs, weights)) + bias
print(f"Hasil Kombinasi Linear (Sebelum Aktivasi): {linear_output}")

print("\n=== HASIL SETELAH MELEWATI FUNGSI AKTIVASI ===")

# Tahap 2: Memasukkan hasil linear ke fungsi aktivasi
output_relu = relu(linear_output)
print(f"1. Output ReLU    : {output_relu}  <- (Jika negatif jadi 0, jika positif tetap)")

output_sigmoid = sigmoid(linear_output)
print(f"2. Output Sigmoid : {output_sigmoid:.4f} <- (Cocok untuk probabilitas Lulus/Tidak)")

output_tanh = tanh(linear_output)
print(f"3. Output Tanh    : {output_tanh:.4f} <- (Rentang -1 hingga 1, pusat di 0)")

# Contoh Softmax (Membutuhkan list nilai dari beberapa neuron output)
outputs_neuron_lain = [linear_output, 2.5, -1.0]
output_softmax = softmax(outputs_neuron_lain)
print(f"4. Output Softmax : {[round(p, 4) for p in output_softmax]} <- (Total probabilitas: {sum(output_softmax)})")

=== PROSES DI DALAM NEURON ===
Hasil Kombinasi Linear (Sebelum Aktivasi): 78.0

=== HASIL SETELAH MELEWATI FUNGSI AKTIVASI ===
1. Output ReLU    : 78.0  <- (Jika negatif jadi 0, jika positif tetap)
2. Output Sigmoid : 1.0000 <- (Cocok untuk probabilitas Lulus/Tidak)
3. Output Tanh    : 1.0000 <- (Rentang -1 hingga 1, pusat di 0)
4. Output Softmax : [1.0, 0.0, 0.0] <- (Total probabilitas: 1.0)


## Contoh Implementasi dengan Python
Berikut adalah contoh kode Python menggunakan library TensorFlow/Keras untuk membangun Neural Network sederhana. Kode ini juga menyertakan tahapan Scaling data menggunakan StandardScaler agar model tidak mengalami kesulitan saat memproses rentang angka yang timpang.

TensorFlow dan Keras adalah dua library (pustaka kode) pemrograman Python yang paling populer dan menjadi standar industri di dunia untuk membangun serta melatih Artificial Intelligence (Kecerdasan Buatan), khususnya dalam bidang Deep Learning dan Neural Network (Jaringan Saraf Tiruan).

Meskipun sering ditulis bersamaan sebagai tensorflow.keras, keduanya awalnya adalah dua hal yang berbeda. Berikut adalah penjelasan mudah untuk memahami peran masing-masing:

1. TensorFlow: "Mesin dan Otot Bawah Tanah"
TensorFlow dikembangkan oleh tim Google Brain. Ibarat membangun sebuah gedung besar, TensorFlow adalah penyedia semen, besi, alat berat, dan pondasi dasarnya.

Cara Kerja: TensorFlow menangani matematika tingkat tinggi yang sangat rumit di belakang layar, seperti perkalian matriks besar, pengelolaan data, dan kalkulasi otomatis saat model sedang belajar (Backpropagation).

Kelebihan: TensorFlow sanggup memproses data berukuran raksasa dan bisa dijalankan tidak hanya di CPU komputer biasa, melainkan di GPU (Kartu Grafis) atau TPU (Tensor Processing Unit) agar proses pelatihan model berjalan ratusan kali lebih cepat.

2. Keras: "Arsitek dan Cetak Biru yang Instan"
Keras awalnya dibuat oleh seorang peneliti AI bernama François Chollet sebagai library mandiri. Keras dirancang dengan prinsip User-Friendly (mudah digunakan manusia).

Cara Kerja: Jika TensorFlow menyediakan bahan bangunan yang rumit, Keras bertindak sebagai struktur lego siap pakai. Daripada Anda menulis ratusan baris kode matematika murni untuk membuat satu lapisan neuron (Layer), Keras mengizinkan Anda membuatnya hanya dengan satu baris perintah instan (misalnya: Dense(units=8)).

Kelebihan: Sangat cepat untuk eksperimen. Anda bisa mendesain arsitektur Neural Network yang rumit hanya dalam hitungan menit.

In [9]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, classification_report
import tensorflow as tf
from tensorflow.keras.models import Sequential # type: ignore
from tensorflow.keras.layers import Dense, Input # type: ignore
import warnings
warnings.filterwarnings('ignore')

# MEMBUAT DATASET SIMULASI (DUMMY DATA)
# Fitur (X): [Jam Belajar, Kehadiran, Nilai Praktik]
# Label (Y): 0 = Tidak Lulus, 1 = Lulus

np.random.seed(42)
X_large = np.random.randint(low=[3, 60, 50], high=[20, 100, 100], size=(1000, 3)).astype(float)
y_large = np.random.randint(0, 2, size=(1000, 1)).astype(float)

print("Dataset berhasil dibuat:")
print(f"Bentuk X: {X_large.shape}")
print(f"Bentuk y: {y_large.shape}")
print(f"\nContoh 5 baris data:\n{X_large[:5]}")
print(f"\nContoh 5 label:\n{y_large[:5].flatten()}")

# Split data menjadi Training (80%) dan Testing (20%)

X_train_large, X_test_large, y_train_large, y_test_large = train_test_split(
    X_large, y_large, test_size=0.2, random_state=42
)

print(f"Data Training: {X_train_large.shape}")
print(f"Data Testing:  {X_test_large.shape}")
print(f"Label Training: {y_train_large.shape}")
print(f"Label Testing:  {y_test_large.shape}")

# Scaling data menggunakan StandardScaler (SANGAT PENTING!)

scaler_large = StandardScaler()
X_train_scaled_large = scaler_large.fit_transform(X_train_large)
X_test_scaled_large = scaler_large.transform(X_test_large)

print("Data berhasil di-scale:")
print(f"Bentuk X_train_scaled: {X_train_scaled_large.shape}")
print(f"Bentuk X_test_scaled:  {X_test_scaled_large.shape}")
print(f"\nStatistik X_train_scaled (mean ≈ 0, std ≈ 1):")
print(f"Mean: {X_train_scaled_large.mean(axis=0)}")
print(f"Std:  {X_train_scaled_large.std(axis=0)}")

# Membangun Arsitektur Neural Network
model = Sequential([
    Input(shape=(3,)),
    Dense(4, activation='relu'),
    Dense(1, activation='sigmoid')
])

# Mengompilasi Model
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# Proses Pelatihan
print("--- Memulai Proses Pelatihan Model dengan Dataset Besar ---")
model.fit(X_train_scaled_large, y_train_large, epochs=100, verbose=0)
print("Pelatihan selesai.\n")

# Evaluasi model pada data pengujian
loss, accuracy = model.evaluate(X_test_scaled_large, y_test_large, verbose=0)
print(f"Akurasi Model pada Data Pengujian: {accuracy:.4f}")

Dataset berhasil dibuat:
Bentuk X: (1000, 3)
Bentuk y: (1000, 1)

Contoh 5 baris data:
[[ 9. 88. 64.]
 [13. 67. 70.]
 [ 9. 78. 72.]
 [13. 70. 73.]
 [ 6. 99. 73.]]

Contoh 5 label:
[0. 1. 0. 0. 1.]
Data Training: (800, 3)
Data Testing:  (200, 3)
Label Training: (800, 1)
Label Testing:  (200, 1)
Data berhasil di-scale:
Bentuk X_train_scaled: (800, 3)
Bentuk X_test_scaled:  (200, 3)

Statistik X_train_scaled (mean ≈ 0, std ≈ 1):
Mean: [-1.37390099e-16 -1.84062834e-16 -5.27702881e-16]
Std:  [1. 1. 1.]
--- Memulai Proses Pelatihan Model dengan Dataset Besar ---
Pelatihan selesai.

Akurasi Model pada Data Pengujian: 0.5350


### Menyimpan Model 

In [10]:
# Menyimpan model ke file
model_save_path = 'model_kelulusan_smk.keras'
model.save(model_save_path)

print(f"Model berhasil disimpan ke: {model_save_path}")

Model berhasil disimpan ke: model_kelulusan_smk.keras


### Pengujian Model yang tersimpan

In [11]:
import tensorflow as tf
import numpy as np

# Muat kembali model yang sudah disimpan
loaded_model = tf.keras.models.load_model('model_kelulusan_smk.keras')

print("Model berhasil dimuat kembali.")

# Buat data input baru (contoh siswa baru)
# Fitur: [Jam Belajar, % Kehadiran, Nilai Praktik]
new_student_data = np.array([
    [14, 90, 85],  # Siswa A: Rajin, kehadiran baik, nilai praktik bagus
    [6, 75, 60],   # Siswa B: Kurang rajin, kehadiran dan nilai praktik standar
    [20, 99, 95]   # Siswa C: Sangat rajin, kehadiran dan nilai praktik sangat bagus
])

# Skalakan data input baru menggunakan scaler yang sama dengan data pelatihan
# Pastikan `scaler_large` sudah tersedia dari sel sebelumnya (29aa284c)
if 'scaler_large' in locals():
    new_student_data_scaled = scaler_large.transform(new_student_data)
    print("Data input baru berhasil diskalakan.")
else:
    print("Error: `scaler_large` tidak ditemukan. Pastikan sel pembuatan dataset besar telah dijalankan.")
    new_student_data_scaled = new_student_data # Lanjutkan tanpa scaling jika scaler tidak ditemukan (hati-hati)

# Lakukan prediksi dengan model yang dimuat
predictions_probabilities = loaded_model.predict(new_student_data_scaled, verbose=0)
predictions_classes = (predictions_probabilities >= 0.5).astype(int)

print("\nHasil Prediksi untuk Data Siswa Baru:")
for i, student in enumerate(new_student_data):
    prob = predictions_probabilities[i][0]
    status = 'LULUS' if predictions_classes[i][0] == 1 else 'TIDAK LULUS'
    print(f"Siswa {chr(65+i)} (Jam Belajar: {student[0]}, Kehadiran: {student[1]}%, Nilai Praktik: {student[2]}):")
    print(f"  Probabilitas Kelulusan: {prob:.4f}")
    print(f"  Status Prediksi: {status}\n")

Model berhasil dimuat kembali.
Data input baru berhasil diskalakan.

Hasil Prediksi untuk Data Siswa Baru:
Siswa A (Jam Belajar: 14, Kehadiran: 90%, Nilai Praktik: 85):
  Probabilitas Kelulusan: 0.4625
  Status Prediksi: TIDAK LULUS

Siswa B (Jam Belajar: 6, Kehadiran: 75%, Nilai Praktik: 60):
  Probabilitas Kelulusan: 0.5248
  Status Prediksi: LULUS

Siswa C (Jam Belajar: 20, Kehadiran: 99%, Nilai Praktik: 95):
  Probabilitas Kelulusan: 0.4992
  Status Prediksi: TIDAK LULUS

